
---
  - name: Установить зависимости
    ansible.builtin.yum:
      name:
        - dnf-plugins-core
      state: present
  
  - name: Добавить официальный репозиторий Docker
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  
  - name: Установить Docker
    ansible.builtin.yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: present
  
  - name: Запустить и включить Docker
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: true
  
  - name: Проверить наличие Docker
    command: docker --version
    register: docker_version
    failed_when: docker_version.rc != 0
    changed_when: false

  - name: Скопировать файл microservice.py
    ansible.builtin.copy:
      src: ../../../../microservice.py
      dest: /home/vagrant/microservice.py
      mode: '0644'
      
  - name: Создать Docker образ для микросервиса
    community.docker.docker_image:
      name: "microsrv_image"
      build:
        path: "/home/vagrant"
      source: build
      tag: latest
      state: present

  - name: Запустить контейнер с микросервисом
    community.docker.docker_container:
      name: microsrv_container
      image: microsrv_image:latest
      state: started
      restart_policy: always
      published_ports:
        - "8080:8080"
  











